export PATH=/Users/bbierman/bin:/usr/local/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:$PATH
export HOMEBREW_GITHUB_API_TOKEN="api-key"
# export PYTHONPATH=/usr/local/lib/python2.7/site-packages/
#. /Library/Python/2.7/site-packages/powerline/bindings/bash/powerline.sh
alias df='df -h'
alias free='free -g'
alias du='du -h'
alias ll='ls -lh'
alias la='ls -alh'
alias updatedb='sudo /usr/libexec/locate.updatedb'
alias fuck='sudo $(history -p \!\!)'

function bliff(){
  pushd /Users/bbierman/bin/TekDefense-Automater
  ./Automater.py -r -w output.html "$1"
  popd
}

function title {
      echo -ne "\033]0;"$*"\007"
}

export HOMEBREW_GITHUB_API_TOKEN=api-key


echo
fortune

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Setting PATH for Python 3.8
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
export PATH
