description = "Bastion host connections across all pods"
session = "bastion"
directory = "~"
pre_commands = [
    "sft resolve bastion241.us001-prod.rtkwlf.io",
]

[[windows]]
name = "bastions"
layout = "tiled"

[[windows.panes]]
title = "us001"
command = "ssh bastion243.us001-prod.rtkwlf.io"

[[windows.panes]]
title = "us002"
split = "h"
percent = 33
command = "ssh bastion243.us002-prod.rtkwlf.io"

[[windows.panes]]
title = "us003"
split = "v"
command = "ssh bastion243.us003-prod.rtkwlf.io"

[[windows.panes]]
title = "ca001"
split = "h"
command = "ssh bastion243.ca001-prod.rtkwlf.io"

[[windows.panes]]
title = "eu001"
split = "v"
command = "ssh bastion243.eu001-prod.rtkwlf.io"

[[windows.panes]]
title = "au001"
split = "v"
command = "ssh bastion243.au001-prod.rtkwlf.io"
